before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: .
    binary: query-aws-logs
    goos:
      - linux
      - windows
      - darwin
    ldflags: -X main.version={{.Version}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: bananaumai
      name: homebrew-query-aws-logs
    homepage: 'https://github.com/bananaumai/query-aws-logs'
    description: 'A tool helping you to explore logs in AWS CloudWatch Logs'
    license: MIT
